# Generated by Django 3.2.20 on 2024-03-16 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VAN', models.FloatField()),
                ('TIR', models.FloatField()),
                ('TRI', models.FloatField()),
                ('LEC', models.FloatField()),
                ('BPM', models.FloatField()),
                ('n', models.IntegerField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
