# Generated by Django 3.2.20 on 2024-03-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators',
            name='BPM',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='LEC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='TIR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='TRI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='VAN',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='n',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
