# Generated by Django 3.2.20 on 2024-04-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_alter_indicators_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicators',
            name='Z',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
