# Generated by Django 3.2.20 on 2024-04-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_indicators_last_z_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicators',
            name='last_Z_update',
        ),
    ]
